### ISSUE TITLE
Need a way to ignore certain URLs

### ISSUE THREAD

**Issue by aneilbaboo** [linkedin/sepia#25]
In my integration tests, I interact both with external services and a local database (DynamoDB).  I need sepia to capture external service requests but pass through requests to my database.

Is there a way to ignore certain URLs?

**Comment by palmerj3** [comment]
@aneilbaboo this can be accomplished like so (when you configure sepia):

```
sepia.filter({
  url: /localhost/i,
  forceLive: true
});
```

**Comment by aneilbaboo** [comment]
Thanks.
