### ISSUE TITLE
content-length=0 requests don't have a body

### ISSUE THREAD

**Issue by rstacruz** [linkedin/sepia#7]
when caching a request that returns `content-length: 0`, it seems `request()` returns a `res.body` that's undefined.

**Comment by avik-das** [comment]
Hi. Thanks for reporting this! Can you provide a small test case that shows this? I'm trying to reproduce this, but I always get back an empty string. Thanks!

**Comment by rstacruz** [comment]
This might be a different problem, sorry :)
